### ISSUE TITLE
problem when updating properties. 

### ISSUE THREAD

**Issue by simonwallin** [QBNK/qbank3api-phpwrapper#1]
Im trying to update properties of an entry via the api. However, any changes or additions I add to a list isn't checked or verified against the lists vocabulary until I manually click save in the GUI. I,m basically looking for a way to programatically save changes.  Is this possible?

**Comment by bohemima** [comment]
Hi,

Not sure exactly what the question is here, updating properties on a media is done via `$api->media()->updateProperties()`-method (https://github.com/QBNK/qbank3api-phpwrapper/blob/1e81f613e9871766479e8e25834b492150c0aec1/Controller/MediaController.php#L601)

For List/Dropdown property-types, the API will not enforce that the value entered is valid, this is by design and is up to the implementer to handle (hint `$api->propertysets()->listPropertyTypes()`)
